version: '3.9'
services:
  weather-app:
    build: .
    platform: linux/arm64
    container_name: weather-app
    restart: always
    ports:
      - "5000:5000"
    command: python app.py
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres-db
    platform: linux/arm64
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherdb
    restart: always
    volumes:
      - /media/madeline/260A-8EA5/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"