
services:
  weather-app:
    build: .
    platform: linux/arm64
    container_name: weather-app
    restart: always
    ports:
      - "5000:5000"
    command: python app.py
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres-db
    platform: linux/arm64
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "weatherdb"]
      interval: 10s
      retries: 5
    volumes:
      - /media/madeline/260A-8EA5/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
      GF_LOG_LEVEL: debug
    depends_on:
      postgres:
        condition: service_healthy

